#!/usr/bin/env python3
"""Generate context_map.json — a mini import-dependency graph of backend/app.

Why a generator instead of a hand-written map: a hand-maintained dependency
map goes stale on the very next commit (AUTONOMY_PROTOCOL.md's Critic
objection to "visual maps"). This script derives the graph from the actual
`import` / `from ... import ...` statements via the stdlib `ast` module, so
it is always truthful when regenerated — which validation_protocol.md
requires whenever module-level imports change.

Usage:
    python3 tools/gen_context_map.py            # print to stdout
    python3 tools/gen_context_map.py --write     # overwrite context_map.json
"""

from __future__ import annotations

import argparse
import ast
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
APP_DIR = ROOT / "backend" / "app"
PACKAGE = "app"


def module_name(path: Path) -> str:
    rel = path.relative_to(APP_DIR.parent).with_suffix("")
    parts = rel.parts
    if parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(parts)


def internal_imports(path: Path, all_modules: set[str]) -> list[str]:
    """Return the sorted set of in-package modules this file imports."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    found: set[str] = set()
    this_module = module_name(path)
    package_parts = this_module.split(".")[:-1]  # dir containing this file

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.startswith(f"{PACKAGE}.") or alias.name == PACKAGE:
                    found.add(alias.name)
        elif isinstance(node, ast.ImportFrom):
            if node.level == 0 and node.module and node.module.startswith(PACKAGE):
                found.add(node.module)
            elif node.level > 0:
                # relative import: resolve against this file's package
                base = package_parts[: len(package_parts) - (node.level - 1)] or [PACKAGE]
                target = ".".join(base) if not node.module else ".".join([*base, node.module])
                found.add(target)

    # keep only modules that actually exist in this project
    return sorted(m for m in found if m in all_modules and m != this_module)


def build_map() -> dict:
    files = sorted(APP_DIR.rglob("*.py"))
    modules = {module_name(f): f for f in files}
    all_modules = set(modules)

    graph: dict[str, dict] = {}
    imported_by: dict[str, set[str]] = {m: set() for m in all_modules}

    for mod, path in modules.items():
        deps = internal_imports(path, all_modules)
        graph[mod] = {
            "file": str(path.relative_to(ROOT)),
            "imports": deps,
        }
        for dep in deps:
            imported_by[dep].add(mod)

    for mod in graph:
        graph[mod]["imported_by"] = sorted(imported_by[mod])

    return {
        "$schema_note": (
            "Generated by tools/gen_context_map.py — do not hand-edit. "
            "Regenerate after any change to module-level imports "
            "(validation_protocol.md step 2)."
        ),
        "package_root": str(APP_DIR.relative_to(ROOT)),
        "modules": graph,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write", action="store_true", help="write to context_map.json instead of stdout"
    )
    args = parser.parse_args()

    data = build_map()
    text = json.dumps(data, indent=2, ensure_ascii=False, sort_keys=True) + "\n"

    if args.write:
        (ROOT / "context_map.json").write_text(text, encoding="utf-8")
        print(f"wrote context_map.json ({len(data['modules'])} modules)", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
